BayesFilters Library: bfl::WhiteNoiseAcceleration Class Reference
bfl::WhiteNoiseAcceleration Class Reference
#include <WhiteNoiseAcceleration.h>
Public Member Functions
WhiteNoiseAcceleration (float T, float tilde_q, unsigned int seed) noexcept
WhiteNoiseAcceleration (float T, float tilde_q) noexcept
WhiteNoiseAcceleration () noexcept
WhiteNoiseAcceleration (const WhiteNoiseAcceleration &wna)
WhiteNoiseAcceleration (WhiteNoiseAcceleration &&wna) noexcept
virtual ~WhiteNoiseAcceleration () noexcept
WhiteNoiseAcceleration & operator= (const WhiteNoiseAcceleration &wna)
WhiteNoiseAcceleration & operator= (WhiteNoiseAcceleration &&wna) noexcept
void propagate (const Eigen::Ref< const Eigen::MatrixXf > &cur_states, Eigen::Ref< Eigen::MatrixXf > prop_states) override
void motion (const Eigen::Ref< const Eigen::MatrixXf > &cur_states, Eigen::Ref< Eigen::MatrixXf > prop_states) override
Eigen::MatrixXf getNoiseSample (const int num) override
Eigen::MatrixXf getNoiseCovarianceMatrix () override
bool setProperty (const std::string &property) override
Protected Attributes
float T_
Eigen::Matrix4f F_
Eigen::Matrix4f Q_
float tilde_q_
Eigen::Matrix4f sqrt_Q_
std::mt19937_64 generator_
std::normal_distribution< float > distribution_
std::function< float()> gauss_rnd_sample_
Detailed Description
Definition at line 14 of file WhiteNoiseAcceleration.h.
Constructor & Destructor Documentation
WhiteNoiseAcceleration() [1/5]
WhiteNoiseAcceleration::WhiteNoiseAcceleration (float T, float tilde_q, unsigned int seed) noexcept
Definition at line 12 of file WhiteNoiseAcceleration.cpp.
WhiteNoiseAcceleration() [2/5]
WhiteNoiseAcceleration::WhiteNoiseAcceleration (float T, float tilde_q) noexcept
Definition at line 34 of file WhiteNoiseAcceleration.cpp.
WhiteNoiseAcceleration() [3/5]
WhiteNoiseAcceleration::WhiteNoiseAcceleration () noexcept
Definition at line 38 of file WhiteNoiseAcceleration.cpp.
WhiteNoiseAcceleration() [4/5]
WhiteNoiseAcceleration::WhiteNoiseAcceleration (const WhiteNoiseAcceleration & wna)
Definition at line 45 of file WhiteNoiseAcceleration.cpp.
WhiteNoiseAcceleration() [5/5]
WhiteNoiseAcceleration::WhiteNoiseAcceleration (WhiteNoiseAcceleration && wna) noexcept
Definition at line 50 of file WhiteNoiseAcceleration.cpp.
~WhiteNoiseAcceleration()
WhiteNoiseAcceleration::~WhiteNoiseAcceleration () virtual noexcept
Definition at line 42 of file WhiteNoiseAcceleration.cpp.
Member Function Documentation
getNoiseCovarianceMatrix()
MatrixXf WhiteNoiseAcceleration::getNoiseCovarianceMatrix () override virtual
Implements bfl::StateModel.
Definition at line 111 of file WhiteNoiseAcceleration.cpp.
References Q_.
getNoiseSample()
MatrixXf WhiteNoiseAcceleration::getNoiseSample (const int num) override virtual
Implements bfl::StateModel.
Definition at line 101 of file WhiteNoiseAcceleration.cpp.
References gauss_rnd_sample_, and sqrt_Q_.
Referenced by motion().
motion()
void WhiteNoiseAcceleration::motion (const Eigen::Ref< const Eigen::MatrixXf > & cur_states, Eigen::Ref< Eigen::MatrixXf > prop_states) override virtual
Implements bfl::StateModel.
Definition at line 93 of file WhiteNoiseAcceleration.cpp.
References getNoiseSample(), and propagate().
operator=() [1/2]
WhiteNoiseAcceleration & WhiteNoiseAcceleration::operator= (const WhiteNoiseAcceleration & wna)
Definition at line 59 of file WhiteNoiseAcceleration.cpp.
operator=() [2/2]
WhiteNoiseAcceleration & WhiteNoiseAcceleration::operator= (WhiteNoiseAcceleration && wna) noexcept
Definition at line 68 of file WhiteNoiseAcceleration.cpp.
References T_.
propagate()
void WhiteNoiseAcceleration::propagate (const Eigen::Ref< const Eigen::MatrixXf > & cur_states, Eigen::Ref< Eigen::MatrixXf > prop_states) override virtual
Implements bfl::StateModel.
Definition at line 87 of file WhiteNoiseAcceleration.cpp.
References F_.
Referenced by motion().
setProperty()
bool bfl::WhiteNoiseAcceleration::setProperty (const std::string & property) inline override virtual
Implements bfl::StateModel.
Definition at line 41 of file WhiteNoiseAcceleration.h.
Member Data Documentation
distribution_
std::normal_distribution<float> bfl::WhiteNoiseAcceleration::distribution_ protected
Definition at line 51 of file WhiteNoiseAcceleration.h.
F_
Eigen::Matrix4f bfl::WhiteNoiseAcceleration::F_ protected
Definition at line 45 of file WhiteNoiseAcceleration.h.
Referenced by propagate().
gauss_rnd_sample_
std::function<float()> bfl::WhiteNoiseAcceleration::gauss_rnd_sample_ protected
Definition at line 52 of file WhiteNoiseAcceleration.h.
Referenced by getNoiseSample().
generator_
std::mt19937_64 bfl::WhiteNoiseAcceleration::generator_ protected
Definition at line 50 of file WhiteNoiseAcceleration.h.
Q_
Eigen::Matrix4f bfl::WhiteNoiseAcceleration::Q_ protected
Definition at line 46 of file WhiteNoiseAcceleration.h.
Referenced by getNoiseCovarianceMatrix().
sqrt_Q_
Eigen::Matrix4f bfl::WhiteNoiseAcceleration::sqrt_Q_ protected
Definition at line 49 of file WhiteNoiseAcceleration.h.
Referenced by getNoiseSample().
T_
float bfl::WhiteNoiseAcceleration::T_ protected
Definition at line 41 of file WhiteNoiseAcceleration.h.
Referenced by operator=().
tilde_q_
float bfl::WhiteNoiseAcceleration::tilde_q_ protected
Definition at line 47 of file WhiteNoiseAcceleration.h.
The documentation for this class was generated from the following files:
C:/Users/cfantacci/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/WhiteNoiseAcceleration.h
C:/Users/cfantacci/GitHub/bayes-filters-lib/src/BayesFilters/src/WhiteNoiseAcceleration.cpp