BayesFilters Library: bfl::LinearSensor Class Reference
bfl::LinearSensor Class Reference
#include <LinearSensor.h>
Public Member Functions
LinearSensor (float sigma_x, float sigma_y, unsigned int seed) noexcept
LinearSensor (float sigma_x, float sigma_y) noexcept
LinearSensor () noexcept
LinearSensor (const LinearSensor &lin_sense)
LinearSensor (LinearSensor &&lin_sense) noexcept
virtual ~LinearSensor () noexcept
LinearSensor & operator= (const LinearSensor &lin_sense) noexcept
LinearSensor & operator= (LinearSensor &&lin_sense) noexcept
void observe (const Eigen::Ref< const Eigen::MatrixXf > &cur_states, Eigen::Ref< Eigen::MatrixXf > observations) override
void measure (const Eigen::Ref< const Eigen::MatrixXf > &cur_states, Eigen::Ref< Eigen::MatrixXf > measurements) override
Eigen::MatrixXf getNoiseSample (const int num) override
Eigen::MatrixXf getNoiseCovarianceMatrix () override
bool setProperty (const std::string property) override
Protected Attributes
float sigma_x_
float sigma_y_
Eigen::MatrixXf H_
Eigen::Matrix2f R_
Eigen::Matrix2f sqrt_R_
std::mt19937_64 generator_
std::normal_distribution< float > distribution_
std::function< float()> gauss_rnd_sample_
Detailed Description
Definition at line 14 of file LinearSensor.h.
Constructor & Destructor Documentation
LinearSensor() [1/5]
LinearSensor::LinearSensor (float sigma_x, float sigma_y, unsigned int seed) noexcept
Definition at line 10 of file LinearSensor.cpp.
LinearSensor() [2/5]
LinearSensor::LinearSensor (float sigma_x, float sigma_y) noexcept
Definition at line 29 of file LinearSensor.cpp.
LinearSensor() [3/5]
LinearSensor::LinearSensor () noexcept
Definition at line 33 of file LinearSensor.cpp.
LinearSensor() [4/5]
LinearSensor::LinearSensor (const LinearSensor & lin_sense)
Definition at line 40 of file LinearSensor.cpp.
LinearSensor() [5/5]
LinearSensor::LinearSensor (LinearSensor && lin_sense) noexcept
Definition at line 51 of file LinearSensor.cpp.
~LinearSensor()
LinearSensor::~LinearSensor () virtual noexcept
Definition at line 37 of file LinearSensor.cpp.
Member Function Documentation
getNoiseCovarianceMatrix()
MatrixXf LinearSensor::getNoiseCovarianceMatrix () override virtual
Implements bfl::ObservationModel.
Definition at line 118 of file LinearSensor.cpp.
References R_.
getNoiseSample()
MatrixXf LinearSensor::getNoiseSample (const int num) override virtual
Implements bfl::ObservationModel.
Definition at line 108 of file LinearSensor.cpp.
References gauss_rnd_sample_, and sqrt_R_.
Referenced by measure().
measure()
void LinearSensor::measure (const Eigen::Ref< const Eigen::MatrixXf > & cur_states, Eigen::Ref< Eigen::MatrixXf > measurements) override virtual
Implements bfl::ObservationModel.
Definition at line 100 of file LinearSensor.cpp.
References getNoiseSample(), and observe().
observe()
void LinearSensor::observe (const Eigen::Ref< const Eigen::MatrixXf > & cur_states, Eigen::Ref< Eigen::MatrixXf > observations) override virtual
Implements bfl::ObservationModel.
Definition at line 94 of file LinearSensor.cpp.
References H_.
Referenced by measure().
operator=() [1/2]
LinearSensor & LinearSensor::operator= (const LinearSensor & lin_sense) noexcept
Definition at line 66 of file LinearSensor.cpp.
operator=() [2/2]
LinearSensor & LinearSensor::operator= (LinearSensor && lin_sense) noexcept
Definition at line 75 of file LinearSensor.cpp.
References sigma_x_.
setProperty()
bool bfl::LinearSensor::setProperty (const std::string property) inline override virtual
Implements bfl::ObservationModel.
Definition at line 41 of file LinearSensor.h.
Member Data Documentation
distribution_
std::normal_distribution<float> bfl::LinearSensor::distribution_ protected
Definition at line 51 of file LinearSensor.h.
gauss_rnd_sample_
std::function<float()> bfl::LinearSensor::gauss_rnd_sample_ protected
Definition at line 52 of file LinearSensor.h.
Referenced by getNoiseSample().
generator_
std::mt19937_64 bfl::LinearSensor::generator_ protected
Definition at line 50 of file LinearSensor.h.
H_
Eigen::MatrixXf bfl::LinearSensor::H_ protected
Definition at line 46 of file LinearSensor.h.
Referenced by observe().
R_
Eigen::Matrix2f bfl::LinearSensor::R_ protected
Definition at line 47 of file LinearSensor.h.
Referenced by getNoiseCovarianceMatrix().
sigma_x_
float bfl::LinearSensor::sigma_x_ protected
Definition at line 41 of file LinearSensor.h.
Referenced by operator=().
sigma_y_
float bfl::LinearSensor::sigma_y_ protected
Definition at line 45 of file LinearSensor.h.
sqrt_R_
Eigen::Matrix2f bfl::LinearSensor::sqrt_R_ protected
Definition at line 49 of file LinearSensor.h.
Referenced by getNoiseSample().
The documentation for this class was generated from the following files:
C:/Users/cfantacci/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/LinearSensor.h
C:/Users/cfantacci/GitHub/bayes-filters-lib/src/BayesFilters/src/LinearSensor.cpp