BayesFilters Library: bfl::VisualParticleFilter Class Reference
bfl::VisualParticleFilter Class Reference abstract
#include <VisualParticleFilter.h>
Public Member Functions
void setInitialization (std::unique_ptr< Initialization > prediction)
void setPrediction (std::unique_ptr< PFPrediction > prediction)
void setCorrection (std::unique_ptr< PFVisualCorrection > correction)
void setResampling (std::unique_ptr< Resampling > resampling)
virtual bool skip (const std::string &what_step, const bool status) override
bool boot ()
void run ()
bool wait ()
void reset ()
void reboot ()
bool teardown ()
unsigned int getFilteringStep ()
bool isRunning ()
Protected Member Functions
VisualParticleFilter () noexcept
virtual ~VisualParticleFilter () noexcept
VisualParticleFilter (VisualParticleFilter &&pf) noexcept
VisualParticleFilter & operator= (VisualParticleFilter &&pf) noexcept
virtual void initialization ()=0
virtual void filteringStep ()=0
virtual void getResult ()=0
virtual bool runCondition ()=0
Protected Attributes
std::unique_ptr< Initialization > initialization_
std::unique_ptr< PFPrediction > prediction_
std::unique_ptr< PFVisualCorrection > correction_
std::unique_ptr< Resampling > resampling_
Detailed Description
Definition at line 17 of file VisualParticleFilter.h.
Constructor & Destructor Documentation
VisualParticleFilter() [1/2]
VisualParticleFilter::VisualParticleFilter () protected noexcept
Definition at line 6 of file VisualParticleFilter.cpp.
~VisualParticleFilter()
VisualParticleFilter::~VisualParticleFilter () protected virtual noexcept
Definition at line 9 of file VisualParticleFilter.cpp.
VisualParticleFilter() [2/2]
VisualParticleFilter::VisualParticleFilter (VisualParticleFilter && pf) protected noexcept
Definition at line 12 of file VisualParticleFilter.cpp.
Member Function Documentation
boot()
bool FilteringAlgorithm::boot () inherited
Definition at line 8 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_, and bfl::FilteringAlgorithm::filteringRecursion().
filteringStep()
virtual void bfl::FilteringAlgorithm::filteringStep () protected pure virtual inherited
Implemented in bfl::SIS, bfl::UnscentedKalmanFilter, and bfl::KalmanFilter.
Referenced by bfl::FilteringAlgorithm::filteringRecursion().
getFilteringStep()
unsigned int FilteringAlgorithm::getFilteringStep () inherited
Definition at line 86 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_step_.
getResult()
virtual void bfl::FilteringAlgorithm::getResult () protected pure virtual inherited
Implemented in bfl::SIS, bfl::UnscentedKalmanFilter, and bfl::KalmanFilter.
initialization()
virtual void bfl::FilteringAlgorithm::initialization () protected pure virtual inherited
Implemented in bfl::SIS, bfl::UnscentedKalmanFilter, and bfl::KalmanFilter.
Referenced by bfl::FilteringAlgorithm::filteringRecursion(), setInitialization(), and bfl::ParticleFilter::setInitialization().
isRunning()
bool FilteringAlgorithm::isRunning () inherited
Definition at line 92 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::run_.
operator=()
VisualParticleFilter & VisualParticleFilter::operator= (VisualParticleFilter && pf) protected noexcept
Definition at line 19 of file VisualParticleFilter.cpp.
reboot()
void FilteringAlgorithm::reboot () inherited
Definition at line 66 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, bfl::FilteringAlgorithm::reset_, and bfl::FilteringAlgorithm::run_.
reset()
void FilteringAlgorithm::reset () inherited
Definition at line 60 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::reset_.
run()
void FilteringAlgorithm::run () inherited
Definition at line 26 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::cv_run_, bfl::FilteringAlgorithm::mtx_run_, and bfl::FilteringAlgorithm::run_.
runCondition()
virtual bool bfl::FilteringAlgorithm::runCondition () protected pure virtual inherited
Implemented in bfl::SIS.
Referenced by bfl::FilteringAlgorithm::filteringRecursion().
setCorrection()
void VisualParticleFilter::setCorrection (std::unique_ptr< PFVisualCorrection > correction)
Definition at line 42 of file VisualParticleFilter.cpp.
References correction_.
setInitialization()
void VisualParticleFilter::setInitialization (std::unique_ptr< Initialization > prediction)
Definition at line 30 of file VisualParticleFilter.cpp.
References bfl::FilteringAlgorithm::initialization(), and initialization_.
setPrediction()
void VisualParticleFilter::setPrediction (std::unique_ptr< PFPrediction > prediction)
Definition at line 36 of file VisualParticleFilter.cpp.
References prediction_.
setResampling()
void VisualParticleFilter::setResampling (std::unique_ptr< Resampling > resampling)
Definition at line 48 of file VisualParticleFilter.cpp.
References resampling_.
skip()
bool VisualParticleFilter::skip (const std::string & what_step, const bool status) override virtual
Implements bfl::FilteringAlgorithm.
Definition at line 54 of file VisualParticleFilter.cpp.
References correction_, and prediction_.
teardown()
bool FilteringAlgorithm::teardown () inherited
Definition at line 75 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::teardown_.
wait()
bool FilteringAlgorithm::wait () inherited
Definition at line 34 of file FilteringAlgorithm.cpp.
References bfl::FilteringAlgorithm::filtering_thread_.
Member Data Documentation
correction_
std::unique_ptr<PFVisualCorrection> bfl::VisualParticleFilter::correction_ protected
Definition at line 41 of file VisualParticleFilter.h.
Referenced by setCorrection(), and skip().
initialization_
std::unique_ptr<Initialization> bfl::VisualParticleFilter::initialization_ protected
Definition at line 39 of file VisualParticleFilter.h.
Referenced by setInitialization().
prediction_
std::unique_ptr<PFPrediction> bfl::VisualParticleFilter::prediction_ protected
Definition at line 40 of file VisualParticleFilter.h.
Referenced by setPrediction(), and skip().
resampling_
std::unique_ptr<Resampling> bfl::VisualParticleFilter::resampling_ protected
Definition at line 42 of file VisualParticleFilter.h.
Referenced by setResampling().
The documentation for this class was generated from the following files:
C:/Users/cfantacci/GitHub/bayes-filters-lib/src/BayesFilters/include/BayesFilters/VisualParticleFilter.h
C:/Users/cfantacci/GitHub/bayes-filters-lib/src/BayesFilters/src/VisualParticleFilter.cpp